##################################################
### SMP - Das SMP Plugin vom Xite SMP Server   ###
###                                            ###
### Source-Code: https://github.com/Xitee1/SMP ###
##################################################
sql:
  type: sqlite # Available: sqlite, mysql
  table-prefix: 'smp_'
  sqlite:
    path: SMP/database.db
  mysql:
    host: '127.0.0.1'
    port: 3306
    user: 'admin'
    password: 'password'
    database: 'smp'
    useSSL: true

discord:
  enabled: false
  token: 'xxx'
  chatChannel: 'chat'

trustlevel:
  6:
    perms:
      - 'spartan.bypass'
      - 'spartan.punishment'
      - 'spartan.admin'

##############
### Blöcke ###
##############
interactAllowedTrustLevel1:
  - ACACIA_PRESSURE_PLATE
  - BIRCH_PRESSURE_PLATE
  - CRIMSON_PRESSURE_PLATE
  - DARK_OAK_PRESSURE_PLATE
  - HEAVY_WEIGHTED_PRESSURE_PLATE
  - JUNGLE_PRESSURE_PLATE
  - LIGHT_WEIGHTED_PRESSURE_PLATE
  - OAK_PRESSURE_PLATE
  - POLISHED_BLACKSTONE_PRESSURE_PLATE
  - SPRUCE_PRESSURE_PLATE
  - STONE_PRESSURE_PLATE
  - WARPED_PRESSURE_PLATE
  - SPRUCE_BUTTON
  - CHEST
  - HOPPER
  - CHEST_MINECART
  - HOPPER_MINECART
  - FURNACE_MINECART
  - ACACIA_DOOR
  - BIRCH_DOOR
  - CRIMSON_DOOR
  - DARK_OAK_DOOR
  - JUNGLE_DOOR
  - OAK_DOOR
  - SPRUCE_DOOR
  - WARPED_DOOR
dangerousBlocks:
  - LAVA_BUCKET
  - FLINT_AND_STEEL

debug: false

# DO NOT TOUCH BELOW THIS LINE
databaseVersion: 3