name: SMP
version: 1
author: Xitee
main: de.xite.smp.main.Main
depend: [CoreProtect]
softdepend: [Spartan]
api-version: 1.20
commands:
  trustlevel:
  tl:
  chunkinfo:
  ci:
  blockinfo:
  bi:
  spielzeit:
  playtime:
  sz:
  pt:
  hilfe:
  help:
  setlocation: