name: SMP
version: 1.2
author: Xitee
main: de.xite.smp.main.Main
depend: [CoreProtect, Spartan]
api-version: 1.20
commands:
  trustlevel:
  chunkinfo:
  ci:
  blockinfo:
  bi:
  spielzeit:
  playtime:
  hilfe:
  help: